# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
- group: Relayworks

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli@18.0.2
    npm install --force
    ng build --configuration production
  displayName: 'npm install and build'

- task: ArchiveFiles@2
  displayName: 'Archive files'
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false
    archiveType: zip
    archiveFile: $(Build.ArtifactStagingDirectory)/relayworks-web.zip
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/relayworks-web.zip'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- task: AzureWebApp@1
  inputs:
    azureSubscription: '$(subscriptionName)'
    appType: 'webAppLinux'
    appName: 'relayworks-web'
    deployToSlotOrASE: true
    resourceGroupName: '$(resourceGroupName)'
    slotName: 'production'
    package: '$(Build.ArtifactStagingDirectory)/relayworks-web.zip'
    runtimeStack: 'NODE|18-lts'
    deploymentMethod: zipDeploy
    startUpCommand: pm2 serve /home/site/wwwroot --no-daemon --spa
